WCF_Assignment_2/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WCF_Assignment_2.EmployeeService;

namespace WCF_Assignment_2.Models

{
    public class EmployeeViewModel
    {
        public Employee Employee { get; set; }

        public List<Employee> EmployeeList { get; set; }
    }
}

WCF_Assignment_2/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCF_Assignment_2.EmployeeService;
using WCF_Assignment_2.Models;

namespace WCF_Assignment_2.Controllers
{
    public class EmployeeController : Controller
    {
        EmpServiceClient client = new EmpServiceClient("BasicHttpBinding_IEmpService");
        // GET: Employee
        public ActionResult Index(int? Id)
        {
            
            EmployeeViewModel empViewModel = new EmployeeViewModel();

            if(Id !=null)
            {
                empViewModel.Employee = client.GetEmployeeById(Id);
            }
            
            empViewModel.EmployeeList = client.GetAllEmployee();
            
            return View(empViewModel);
        }

        [HttpPost]
        public ActionResult AddorUpdate(Employee employee)
        {
            //EmployeeViewModel empViewModel = new EmployeeViewModel();
            if (employee.Id != 0)
                client.UpdateEmployee(employee);
            else
                client.InsertEmployee(employee);

            return Json(new { status = "Success" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            //EmployeeViewModel empViewModel = new EmployeeViewModel();
            client.DeleteEmployee(Id);

            return Json(new { status = "Success" }, JsonRequestBehavior.AllowGet);
        }
    }

}

WCF_Assignment_2/Controllers/TempreatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCF_Assignment_2.EmployeeService;

namespace WCF_Assignment_2.Controllers
{
    public class TempreatureController : Controller
    {
        EmpServiceClient client = new EmpServiceClient("BasicHttpBinding_IEmpService");
        // GET: Tempreature
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult celtoFar(int value)
        {
            double output = client.CelsiustoFahrenheit(value);

            return Json( new { output = output  }, JsonRequestBehavior.AllowGet );
        }

        [HttpPost]
        public ActionResult FartoCel(int value)
        {
            double output = client.FahrenheittoCelcius(value);

            return Json(new { output = output }, JsonRequestBehavior.AllowGet);
        }
    }
}

WCF_Assignment_2/Views/Employee/Index.cshtml
@model WCF_Assignment_2.Models.EmployeeViewModel

@{
    ViewBag.Title = "Index";
}
<div id="divEmployeeForm">
    @using (Html.BeginForm("AddorUpdate", "Employee", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Employee.Id);
        <div class="col-lg-12">
            <h1 class="panel-heading">Employee</h1>

        </div>
        <div class="container">
            <div class="panel-default">
                <input type="hidden" id="CustomerId" />
                <div id="customerForm" class="col-lg-4">
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Employee.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Employee.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Employee.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Employee.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Employee.Gender, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Employee.Gender, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Employee.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Employee.Salary, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Employee.Salary, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row" style="margin-left:35%">
                        <button type="submit" id="btnsave" class="btn btn-primary">Save</button>

                        <button type="reset" id="btnClear" class="btn btn-primary">Clear</button>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <table id="tblEmpDtls" class="table table-bordered table-striped">
                    <tr>


                        <th>
                            @Html.DisplayNameFor(model => model.Employee.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Employee.Gender)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Employee.Salary)
                        </th>
                        <th>Action</th>
                    </tr>

                    @foreach (var Employee in Model.EmployeeList)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => Employee.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Employee.Gender)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Employee.Salary)
                            </td>
                            <td>
                                <a style="cursor:pointer" onclick="GetEmployee(@Employee.Id)">Edit</a> |
                                <a style="cursor:pointer" onclick="DeleteEmployee(@Employee.Id)">Delete</a>
                            </td>


                        </tr>
                    }

                </table>

            </div>

        </div>

    }
</div>

WCF_Assignment_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WCF Service", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employee", "Index", "Employee" )</li>
                    <li>@Html.ActionLink("Tempreature Convertor", "Index", "Tempreature")</li>

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Site.js"></script>
</body>
</html>

WCF_Assignment_2/Views/Tempreature/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>Temprature Convertor</h2>
<div class="container" style="margin:33px 0 0 20%">
    <div class="form-inline">
        <label class="">Enter Value</label>
        <input type="text" name="value" id="txtvalue" class="form-control" />
        <input type="button" class="btn btn-primary" id="btnceltofar" value="Celsius To Fahrenheit" />
        <input type="button" class="btn btn-primary" id="btnfartocel" value="Fahrenheit To Celsius" />
    </div>
    <div class="form-group" style="margin:30px 0 0 10%">
        <h3 id="output"></h3>
    </div>
</div>